# Server port for the Spring Boot application (React uses 5173, Spring will use 8080)
server.port=8080

# MongoDB Connection Configuration
# We connect to the remote MongoDB Atlas cluster.
spring.data.mongodb.uri=mongodb+srv://sabarigirisabarigiri64_db_user:V3otlZCPCAhk1X32@cluster0.f4aklfu.mongodb.net/itams_db?appName=Cluster0

# Enable debug logging for Mongo so we can see queries if needed
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
